<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap | Himalayan Discovery</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #050505;
            color: #ffffff;
            font-size: 14px;
            margin: 0;
            padding: 40px;
          }
          h1 {
            font-family: 'Playfair Display', serif;
            color: #fbbf24;
            font-size: 32px;
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 2px;
          }
          p {
            color: #888;
            margin-bottom: 30px;
            font-size: 12px;
          }
          a {
            color: #fff;
            text-decoration: none;
            transition: color 0.3s ease;
          }
          a:hover {
            color: #fbbf24;
          }
          table {
            border: none;
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
            background: rgba(255,255,255,0.02);
            border-radius: 8px;
            overflow: hidden;
          }
          th {
            background-color: rgba(255,255,255,0.05);
            text-align: left;
            padding: 15px 20px;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 1px;
            color: #fbbf24;
            border-bottom: 1px solid rgba(255,255,255,0.1);
          }
          td {
            padding: 15px 20px;
            border-bottom: 1px solid rgba(255,255,255,0.05);
            color: #ccc;
          }
          tr:hover td {
            background-color: rgba(255,255,255,0.05);
          }
          .url-col { color: #fff; font-family: monospace; }
          .priority-col { color: #fbbf24; font-weight: bold; }
        </style>
      </head>
      <body>
        <div id="content">
          <h1>Himalayan Discovery Sitemap</h1>
          <p>
            This XML Sitemap is generated by Next.js to allow search engines to discover pages on the site.
            <br/>
            Total URLs: <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/>
          </p>
          <table>
            <thead>
              <tr>
                <th width="60%">URL Location</th>
                <th width="15%">Priority</th>
                <th width="15%">Change Freq</th>
                <th width="10%">Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td class="url-col">
                    <xsl:variable name="itemURL">
                      <xsl:value-of select="sitemap:loc"/>
                    </xsl:variable>
                    <a href="{$itemURL}">
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td class="priority-col">
                    <xsl:value-of select="concat(sitemap:priority*100,'%')"/>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:changefreq"/>
                  </td>
                  <td>
                    <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
