export interface SEOPage {
    slug: string;
    title: string;
    subtitle: string;
    heroImage: string;
    introTitle: string;
    introText: string;
    metaTitle: string;
    metaDescription: string;
    relatedTourId: string;
    features: string[];
    weatherInfo: string;
    bestTime: string;
    gettingThere: string;
    thingsToDo: string[];
    faq: { question: string; answer: string }[];
    longContent: string;
}

export const seoPages: SEOPage[] = [
    {
        slug: 'spiti-valley-tour-packages',
        title: 'Spiti Valley Tour Packages',
        subtitle: 'The Middle Land Expedition',
        heroImage: '/visual-journey/langza.png',
        introTitle: 'Welcome to the Cold Desert',
        introText: 'Spiti Valley, the "Middle Land", offers landscapes that seem extraterrestrial.',
        metaTitle: 'Spiti Valley Tour Packages 2026 | Best Spiti Road Trips',
        metaDescription: 'Book the best Spiti Valley tour packages. Explore Key Monastery, Chandratal Lake.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['Ancient Monasteries', 'Highest Post Office', 'Fossil Hunting'],
        weatherInfo: "Spiti remains cold throughout the year. Summers (15-25°C). Winters (-30°C).",
        bestTime: "June to September",
        gettingThere: "By Road: Shimla to Kaza (450km) or Manali to Kaza (200km).",
        thingsToDo: ["Visit Key Monastery", "Post a letter from Hikkim", "Fossil Hunting"],
        faq: [
            { question: "Kunzum Pass opening 2026?", answer: "Expected early June due to low snow this year." },
            { question: "Green Fee for entering Spiti 2026?", answer: "Proposal for ₹200-500 environmental cess per vehicle at Sumdo/Losar checkpost." },
            { question: "Is permis required?", answer: "Only for foreigners (Inner Line Permit). Indians need valid ID." },
            { question: "Best mobile network?", answer: "Jio works best in Kaza. BSNL is fallback." },
            { question: "Can we go in Car?", answer: "SUV/4x4 recommended. Sedans struggle." },
            { question: "ATM availability?", answer: "Only in Kaza (SBI). Often out of cash." },
            { question: "Is it safe for families?", answer: "Yes, but avoid bringing kids under 5 due to altitude." }
        ],
        longContent: `<p>Spiti Valley is not just a destination; it's an emotion. Tucked away in Himachal Pradesh...</p>`
    },
    {
        slug: 'kinnaur-spiti-road-trip',
        title: 'Kinnaur & Spiti Valley Road Trip',
        subtitle: 'The Tribal Circuit',
        heroImage: '/hero/kinnaur.png',
        introTitle: 'The Scenic Tribal Route',
        introText: 'Embark on a journey through the "Land of Gods". Kinnaur offers lush green valleys.',
        metaTitle: 'Kinnaur Spiti Road Trip Itinerary',
        metaDescription: 'Experience the ultimate Kinnaur Spiti road trip via Hindustan Tibet Highway.',
        relatedTourId: 'spiti-kinnaur-adventure',
        features: ['Hindustan Tibet Highway', 'Chitkul', 'Kinner Kailash'],
        weatherInfo: "Kinnaur is pleasant in summer, cold in winter.",
        bestTime: "April to October",
        gettingThere: "Shimla -> Sarahan -> Sangla -> Kalpa.",
        thingsToDo: ["Walk by Baspa River", "Sunset at Kalpa"],
        faq: [
            { question: "Shimla-Kinnaur road status?", answer: "Open. This is the only all-weather access to Spiti." },
            { question: "Road condition in Kinnaur?", answer: "Generally good tar roads, but prone to landslides near Nigulsari." },
            { question: "Is Kinnaur dangerous?", answer: "The 'taranda dhank' is famous for cliffs, but safe with expert drivers." },
            { question: "Can we see Kinner Kailash?", answer: "Yes, visible clearly from Kalpa and Reckong Peo." },
            { question: "Best apples?", answer: "Kinnaur apples are world famous. Harvest season is Sep/Oct." },
            { question: "Is Chitkul open in winter?", answer: "Roads to Chitkul often close due to heavy snow in Jan/Feb." },
            { question: "Food options?", answer: "North Indian and Tibetan food is widely available." }
        ],
        longContent: `<p>The road trip combining Kinnaur and Spiti is often hailed as the "Grand Circle"...</p>`
    },
    {
        slug: 'shimla-to-spiti-taxi-tour',
        title: 'Shimla to Spiti Valley Taxi Tour',
        subtitle: 'Comfortable & Scenic',
        heroImage: '/hero/shimla.png',
        introTitle: 'The Classic Gateway',
        introText: 'Start your ascent from the gentle hills of Shimla. This route allows for gradual acclimatization.',
        metaTitle: 'Shimla to Spiti Taxi Package',
        metaDescription: 'Hire expert drivers for Shimla to Spiti taxi tour.',
        relatedTourId: 'shimla-spiti-overland',
        features: ['Gradual Acclimatization', 'Scenic Drive', 'Experienced Drivers'],
        weatherInfo: "Shimla is pleasant in summers.",
        bestTime: "All year round",
        gettingThere: "Start from Chandigarh/Shimla via NH-5.",
        thingsToDo: ["Explore Shimla", "Rafting in Sutlej", "Bhimakali Temple"],
        faq: [
            { question: "Winter-Ready 4x4 rentals?", answer: "We provide modified 4x4 Scorpios/Thars with snow chains." },
            { question: "Which taxi is best?", answer: "Innova Crysta for comfort, Scorpio/Xylo for ruggedness." },
            { question: "Driver expertise?", answer: "We use only local hill drivers experienced in snow/slush." },
            { question: "Cost of rental?", answer: "Approx ₹4000-5000 per day including driver allowance." },
            { question: "Night driving?", answer: "Strictly avoided for safety reasons." },
            { question: "AC usage?", answer: "AC works in lower hills. In high altitude, windows are best for oxygen." },
            { question: "Hidden charges?", answer: "None. Tolls and parking usually extra or included as per package." }
        ],
        longContent: `<p>Choosing a taxi tour from Shimla to Spiti is the most comfortable and scientifically recommended way...</p>`
    },
    {
        slug: 'chandratal-lake-camping-guide',
        title: 'Chandratal Lake Camping Guide',
        subtitle: 'The Moon Lake',
        heroImage: '/hero/chandratal.png',
        introTitle: 'Camping Under the Milky Way',
        introText: 'Chandratal (Moon Lake) is a crescent-shaped lake located at 4,300 meters.',
        metaTitle: 'Chandratal Lake Camping | Tents & Bookings 2026',
        metaDescription: 'Complete guide to Chandratal Lake camping.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['Luxury Swiss Tents', 'Bonfire Nights', 'Stargazing'],
        weatherInfo: "Extremely cold at night.",
        bestTime: "June to September",
        gettingThere: "14km drive from Batal + 1km trek.",
        thingsToDo: ["Parikrama of lake", "Night photography", "Spotting wildlife"],
        faq: [
            { question: "Chandratal status early 2026?", answer: "Closed till June. Road blocked by snow at Batal." },
            { question: "Can we camp by the lake?", answer: "No, camping is banned near the banks. Campsites are 2km away." },
            { question: "Is there electricity?", answer: "No grid power. Camps use solar lights/generators for few hours." },
            { question: "Restrooms attached?", answer: "Luxury tents have attached toilets. Budget ones have common tents." },
            { question: "Mobile network?", answer: "Zero. Complete digital detox." },
            { question: "Does water freeze?", answer: "Yes, bucket water freezes at night even in summer." },
            { question: "AMS risk?", answer: "High. It's at 14,000ft. Spend a night in Kaza before coming here." }
        ],
        longContent: `<p>Imagine a pristine blue lake surrounded by scree mountains...</p>`
    },
    {
        slug: 'winter-spiti-expedition-4x4',
        title: 'Winter Spiti Expedition 4x4',
        subtitle: 'The White Spiti',
        heroImage: 'https://images.unsplash.com/photo-1518005068251-37900150dfca?auto=format&fit=crop&q=80',
        introTitle: 'A Frozen Fairytale',
        introText: 'Experience Spiti in its rawest form. Temperatures dip to -30°C.',
        metaTitle: 'Winter Spiti Expedition 2026 | Snow Leopard Tour',
        metaDescription: 'Join our Winter Spiti 4x4 Expedition. Spot Snow Leopards.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['Snow Leopard Spotting', 'Frozen Waterfalls', 'Homestays'],
        weatherInfo: "Sub-zero. -5°C to -35°C.",
        bestTime: "January to March",
        gettingThere: "Accessible only via Shimla-Kinnaur route.",
        thingsToDo: ["Snow Leopard Sighting", "Walk on frozen rivers"],
        faq: [
            { question: "Cost of Snow Leopard expedition 2026?", answer: "₹80,000 to ₹1,20,000 per person for a 7-day guided tour." },
            { question: "Chances of spotting Snow Leopard in Feb?", answer: "High (60-70%). It is mating season." },
            { question: "Current temp in Kaza?", answer: "Expect -15°C day to -30°C night." },
            { question: "Mandatory thermal gear?", answer: "Merino wool baselayers, -30°C rated down jacket." },
            { question: "Is Spiti River trek open?", answer: "Yes, walking on frozen river is possible with guides in Jan/Feb." },
            { question: "Vehicle freeze solution?", answer: "Use anti-freeze coolant. Pour hot water on filter." },
            { question: "Snow blindness?", answer: "Wear UV400 sunglasses even on cloudy days. Essential." }
        ],
        longContent: `<p>For the faint-hearted, Spiti is closed in winter. But for the true seeker...</p>`
    },
    {
        slug: 'tribal-circuit-himachal-pradesh',
        title: 'Tribal Circuit Himachal Pradesh',
        subtitle: 'Unexplored Culture',
        heroImage: '/hero/kinnaur.png',
        introTitle: 'Kinnaur & Lahaul-Spiti',
        introText: 'A cultural odyssey through the tribal districts of Himachal.',
        metaTitle: 'Tribal Circuit Tour Himachal',
        metaDescription: 'Explore the tribal circuit. Culture and traditions.',
        relatedTourId: 'rohru-kinnaur-expedition',
        features: ['Ancient Traditions', 'Local Festivals', 'Unique Cuisine'],
        weatherInfo: "Variable. Pleasant in Kinnaur, dry/cold in Spiti.",
        bestTime: "May to October",
        gettingThere: "Loops Shimla -> Manali via Kinnaur/Spiti.",
        thingsToDo: ["Local weddings", "Try Chang", "Visit forts"],
        faq: [
            { question: "Halda Festival 2026?", answer: "Lahaul valley festival, usually mid-January." },
            { question: "Losar with locals?", answer: "Stay in a homestay during Feb to witness festivities." },
            { question: "What tribes live here?", answer: "Kinnauris and Spitians (Bhotias)." },
            { question: "Local alcohol?", answer: "'Arak' or 'Chang' (Barley wine) is traditional." },
            { question: "Dress code?", answer: "Respect local culture. Cover shoulders/knees in temples." },
            { question: "Weaving workshop?", answer: "Women in Kibber weaving cooperative offer demos." },
            { question: "Homestay availability?", answer: "Best way to experience tribal culture." }
        ],
        longContent: `<p>The Tribal Circuit of Himachal Pradesh traverses the districts of Kinnaur and Lahaul-Spiti...</p>`
    },
    {
        slug: 'manali-to-spiti-road-trip',
        title: 'Manali to Spiti Road Trip',
        subtitle: 'The Adventure Route',
        heroImage: '/visual-journey/kunzum.png',
        introTitle: 'Adrenaline Overdrive',
        introText: 'The shortest but toughest route to Spiti. Cross the Rohtang/Atal Tunnel.',
        metaTitle: 'Manali to Spiti Valley Road Trip',
        metaDescription: 'Plan your Manali to Spiti road trip. Itinerary and conditions.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['Atal Tunnel', 'Kunzum Pass', 'Off-roading'],
        weatherInfo: "Unpredictable at Kunzum Pass.",
        bestTime: "mid-June to mid-October",
        gettingThere: "Manali -> Atal Tunnel -> Kunzum -> Kaza.",
        thingsToDo: ["Chandra Dhaba", "Atal Tunnel Photos", "Off-roading"],
        faq: [
            { question: "Kunzum Pass opening 2026?", answer: "Expected early June due to low snow this year." },
            { question: "Malling Nala status?", answer: "New tunnel/bridge work in progress. Expect 30 min delays." },
            { question: "Permit needed?", answer: "Needed for Rohtang Pass. Not for Atal Tunnel route." },
            { question: "Car type?", answer: "High ground clearance essential. 4x4 preferred." },
            { question: "AMS risk?", answer: "Very high as you gain altitude too fast." },
            { question: "Food stops?", answer: "Chhatru and Batal (Chacha-Chachi Dhaba)." },
            { question: "Fuel?", answer: "Fill tank at Manali/Tandi. No pumps till Kaza." }
        ],
        longContent: `<p>The Manali to Spiti route is the adrenaline junkie's choice...</p>`
    },
    {
        slug: 'best-time-to-visit-spiti-valley',
        title: 'Best Time to Visit Spiti Valley',
        subtitle: 'Travel Guide',
        heroImage: 'https://images.unsplash.com/photo-1545652585-703c37351543?auto=format&fit=crop&q=80',
        introTitle: 'Seasons of Spiti',
        introText: 'Every season in Spiti paints a different picture.',
        metaTitle: 'Best Time to Visit Spiti Valley',
        metaDescription: 'When to visit Spiti Valley? Detailed guide.',
        relatedTourId: 'spiti-kinnaur-adventure',
        features: ['Summer (Jun-Sep)', 'Autumn (Oct)', 'Winter (Jan-Mar)'],
        weatherInfo: "Cold desert climate.",
        bestTime: "June to September",
        gettingThere: "Shimla route: All year. Manali: Summer.",
        thingsToDo: ["Plan based on interest", "Check road status"],
        faq: [
            { question: "Seabuckthorn harvest time?", answer: "September. Join locals in harvesting 'Drilbu' berries." },
            { question: "Is monsoon safe?", answer: "Spiti is rain-shadow, so safe. But approach roads get landslides." },
            { question: "When for snow?", answer: "Jan to March." },
            { question: "When for apples?", answer: "September is apple harvest season." },
            { question: "When for road trip?", answer: "June to September is best road condition." },
            { question: "Crowd?", answer: "May/June is busiest. Sep/Oct is quiet." },
            { question: "Budget time?", answer: "End of season (October) might have discounts." }
        ],
        longContent: `<p>One of the most common questions we get is, "When is the best time to visit Spiti?"...</p>`
    },
    {
        slug: 'luxury-spiti-hotels-resorts',
        title: 'Luxury Spiti Hotels & Resorts',
        subtitle: 'Comfort in Wilderness',
        heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80',
        introTitle: 'Glamping & Premium Stays',
        introText: 'Experience premium hospitality with heated rooms.',
        metaTitle: 'Best Luxury Hotels in Spiti Valley',
        metaDescription: 'Book top luxury hotels in Spiti.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['Heated Rooms', 'Organic Meals', 'Best Views'],
        weatherInfo: "Hotels have heating. Outside is cold.",
        bestTime: "May to October",
        gettingThere: "Luxury properties in Kaza, Tabo, Sangla.",
        thingsToDo: ["Luxury suites", "Glamping", "Spa"],
        faq: [
            { question: "Luxury Glamping 2026?", answer: "The Grand Dewachen and Spiti Village Resort are operational." },
            { question: "Are there 5-star hotels?", answer: "No big chains. Only boutique luxury properties." },
            { question: "How to book Heated Homestay?", answer: "Contact us. We partner with homestays using traditional 'Bukhari' heating." },
            { question: "24/7 Hot water?", answer: "Yes, geysers are available." },
            { question: "Wi-Fi in rooms?", answer: "Mostly yes, but speed depends on local towers." },
            { question: "Food quality?", answer: "Excellent multi-cuisine and organic options." },
            { question: "Booking?", answer: "Advance booking essential for top properties." }
        ],
        longContent: `<p>Spiti Valley was once known for backpacker hostels...</p>`
    },
    {
        slug: 'offbeat-places-in-himachal',
        title: 'Offbeat Places in Himachal',
        subtitle: 'Hidden Gems',
        heroImage: '/hero/pabbar.png',
        introTitle: 'Beyond the Tourist Trail',
        introText: 'Discover hidden valleys like Pabbar and Dodra Kwar.',
        metaTitle: 'Offbeat Places in Himachal Pradesh',
        metaDescription: 'Explore hidden gems. Pabbar Valley, Threlangi.',
        relatedTourId: 'rohru-spiti-roadtrip',
        features: ['Pabbar Valley', 'Chanshal Pass', 'Dodra Kwar'],
        weatherInfo: "Pristine and less polluted.",
        bestTime: "Apr-Jun & Sep-Nov",
        gettingThere: "Requires private vehicle.",
        thingsToDo: ["Trout fishing", "Chanshal Trek"],
        faq: [
            { question: "Where is Pabbar Valley?", answer: "East of Shimla, near Rohru." },
            { question: "Is it commercialized?", answer: "No, very raw and untouched." },
            { question: "Road condition?", answer: "Chanshal pass is off-road. Rest is average." },
            { question: "Zero-Waste homestays?", answer: "Look for homestays in remote villages that use solar cookers." },
            { question: "Mobile network?", answer: "Weak in spots. BSNL/Jio work locally." },
            { question: "Fishing?", answer: "Famous for Trout fishing in Pabbar river." },
            { question: "Treks?", answer: "Chanshal to Saru Tal trek is famous." }
        ],
        longContent: `<p>Himachal Pradesh is not just Shimla and Manali...</p>`
    },
    {
        slug: 'spiti-valley-bike-trip',
        title: 'Spiti Valley Bike Trip',
        subtitle: 'Ride of Legends',
        heroImage: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80',
        introTitle: 'Conquer the Himalayas',
        introText: 'Riding a Royal Enfield through the treacherous roads of Spiti is a rite of passage for every biker.',
        metaTitle: 'Spiti Valley Bike Trip 2026 | Manali to Spiti Bike Tour',
        metaDescription: 'Join the ultimate Spiti Valley Bike Trip. Manali to Kaza, Chandratal, and Kunzum Pass on Royal Enfield.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['Royal Enfield 500cc', 'Backup Vehicle', 'Mechanic Support', 'Camping'],
        weatherInfo: "Windy and dusty. Riding gear essential.",
        bestTime: "June to September",
        gettingThere: "Start from Manali or Shimla on bike.",
        thingsToDo: ["Ride across Kunzum Pass", "Off-road to Chandratal", "Group riding"],
        faq: [
            { question: "Bike rentals in winter?", answer: "Closed. Roads are icy. Only locals ride." },
            { question: "Which bike?", answer: "RE Himalayan, XPulse, or 500cc+ cruisers." },
            { question: "Fuel stations?", answer: "Carry 10L jerry can. Tandi to Kaza is 200km without pumps." },
            { question: "Punctures?", answer: "Carry tubeless kit + inflator. Mechanics are rare." },
            { question: "Group size?", answer: "We restrict to 15 bikes for safety." },
            { question: "License?", answer: "Visual ID + Valid DL required." },
            { question: "Water crossings?", answer: "Many nallahs. Ride carefully in first gear." }
        ],
        longContent: `<p>There is no greater feeling than the thump of a Royal Enfield echoing against the barren mountains of Spiti. A <strong>Spiti Valley Bike Trip</strong> is not for the faint-hearted; it tests your endurance, your skill, and your spirit. Crossing water crossings (nallahs) like Malling and Pagal Nallah, riding on the gravel tracks of Losar, and conquering the mighty Kunzum Pass are badges of honor.</p><h3>The Route</h3><p>Most bikers prefer the Manali-Kaza loop for its sheer adrenaline. However, the Shimla-Kinnaur-Spiti route allows for a more gradual ascent. We provide fully serviced bikes, backup vehicles with mechanics, and gear to ensure that your focus remains on the road and the breathtaking vistas.</p>`
    },
    {
        slug: 'spiti-valley-honeymoon-package',
        title: 'Spiti Valley Honeymoon Package',
        subtitle: 'Romantic Wilderness',
        heroImage: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&q=80',
        introTitle: 'Love in the Time of Mountains',
        introText: 'Escape the crowds. Find solitude with your partner in the magical landscapes of Spiti.',
        metaTitle: 'Spiti Valley Honeymoon Package | Romantic Spiti Tour',
        metaDescription: 'Unique honeymoon in Spiti Valley. Luxury glamping, private tours, and candlelight dinners under the stars.',
        relatedTourId: 'luxury-spiti-hotels-resorts',
        features: ['Private Glamping', 'Candlelight Dinner', 'Couple Photography', 'Privacy'],
        weatherInfo: "Cold nights, cozy stays.",
        bestTime: "May to October",
        gettingThere: "Private taxi from Shimla/Manali.",
        thingsToDo: ["Stargazing together", "Walk by the river", "Monastery blessings"],
        faq: [
            { question: "Is it romantic?", answer: "Yes, very secluded and intimate. Stargazing is magical." },
            { question: "Privacy?", answer: "We arrange private tents/rooms away from crowds." },
            { question: "Candlelight dinner?", answer: "Possible at Chandratal camps or premium Kaza hotels." },
            { question: "Photography?", answer: "We can include a photographer." },
            { question: "Is it tiring?", answer: "It involves travel. We keep itinerary relaxed (2 nights per place)." },
            { question: "Couple friendly?", answer: "Totally safe and welcoming." },
            { question: "Best surprise?", answer: "Sunset at Langza Buddha statue." }
        ],
        longContent: `<p>Forget the beaches of Goa or the malls of Dubai. Start your new life together with an adventure. A <strong>Honeymoon in Spiti</strong> is about shared silence, witnessing majestic sunsets hand-in-hand, and counting shooting stars from your tent.</p><h3>Romantic Experiences</h3><p>Stay in luxury tents at Chandratal, offering the privacy and comfort you need. Enjoy a private picnic by the Spiti river. Visit the ancient monasteries to seek blessings for a lifetime of togetherness. Our packages are designed to be slow-paced, ensuring you have ample time to just be with each other.</p>`
    },
    {
        slug: 'kaza-travel-guide',
        title: 'Kaza Travel Guide',
        subtitle: 'The HQ of Spiti',
        heroImage: '/hero/spiti.png',
        introTitle: 'Heart of the Valley',
        introText: 'Kaza is the administrative headquarters and the largest town in Spiti Valley.',
        metaTitle: 'Kaza Travel Guide | Hotels, Places to Visit, Cafes',
        metaDescription: 'Complete travel guide to Kaza. Best cafes, hotels, petrol pump, and ATM status.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['World highest Petrol Pump', 'Cafes', 'Monasteries', 'Market'],
        weatherInfo: "Dry and cold. Windy afternoons.",
        bestTime: "May to October",
        gettingThere: "Main hub. Buses available from Manali/Shimla.",
        thingsToDo: ["Cafe hopping (The Himalayan Cafe)", "Visit Monastery", "Shopping"],
        faq: [
            { question: "Kaza 5G / Starlink?", answer: "Jio 5G is live in Kaza market! Starlink is not legal yet." },
            { question: "Best Wi-Fi cafes in Kaza?", answer: "The Himalayan Cafe and Sol Cafe have reliable fiber connections." },
            { question: "Petrol price Kaza?", answer: "Approx ₹102/L (higher than plains due to transport)." },
            { question: "Buy oxygen in Kaza?", answer: "Chemist shop near Kaza bus stand sells portable cans." },
            { question: "Best Mokthuk in Kaza?", answer: "Taste of Spiti serves authentic mutton mokthuk." },
            { question: "ATMs?", answer: "SBI ATM exists. Sometimes empty. Kaza Co-op bank also there." },
            { question: "Hospital?", answer: "Community Health Center (CHC) is decent for basics." }
        ],
        longContent: `<p>Kaza is the lifeline of Spiti. Situated at 3,800 meters, it is the base for all excursions. It is a mix of traditional culture and modern backpacker vibes. You will find monks with prayer wheels walking alongside bikers in leather jackets.</p><h3>The Market</h3><p>The Kaza market is vibrant, selling everything from prayer flags and singing bowls to sea buckthorn tea. Don't forget to fuel up at the <strong>world's highest retail petrol pump</strong> here.</p>`
    },
    {
        slug: 'key-monastery-spiti',
        title: 'Key Monastery Guide',
        subtitle: 'The Fortress of Faith',
        heroImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&q=80',
        introTitle: '1000 Years of History',
        introText: 'Perched on a conical hill, Key (Ki) Monastery is the largest and most iconic monastery in Spiti.',
        metaTitle: 'Key Monastery Spiti Valley | History & Architecture',
        metaDescription: 'Visit Key Monastery. Experience the cham dance, ancient thangkas, and monk life.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['Ancient Murals', 'Meditation', 'Best Views', 'Monk Life'],
        weatherInfo: "Windy hilltop.",
        bestTime: "May to October",
        gettingThere: "14km from Kaza.",
        thingsToDo: ["Attend morning prayer", "Drink butter tea", "Photography"],
        faq: [
            { question: "Photography in Key Monastery?", answer: "DSLR fee ₹50. No photos inside prayer hall." },
            { question: "Entry fee?", answer: "No fee. Donations accepted." },
            { question: "Timings?", answer: "6 AM to 6 PM generally." },
            { question: "Can we stay?", answer: "Yes, basic guest house available for men/women." },
            { question: "Butter tea?", answer: "Monks often offer herbal tea to visitors in kitchen." },
            { question: "Festival?", answer: "Cham dance (Mask dance) in July is spectacular." },
            { question: "Distance Kaza?", answer: "30-45 mins drive." }
        ],
        longContent: `<p>Looking like a stack of boxes from a distance, <strong>Key Monastery</strong> is a marvel of Pasada style architecture. Founded in the 11th century, it has survived invasions and earthquakes. Inside, navigate through narrow, dark passages to reach prayer halls adorned with rare thangkas and ancient weapons.</p>`
    },
    {
        slug: 'pin-valley-national-park',
        title: 'Pin Valley National Park',
        subtitle: 'Land of Ibex',
        heroImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80',
        introTitle: 'The Green Patch',
        introText: 'Pin Valley is the only cold desert national park in Himachal, known for its biodiversity.',
        metaTitle: 'Pin Valley National Park Tour | Mud Village',
        metaDescription: 'Explore Pin Valley. Home of the Snow Leopard and Ibex. Stay in Mud Village.',
        relatedTourId: 'spiti-kinnaur-adventure',
        features: ['Snow Leopard', 'Siberian Ibex', 'Mud Village', 'Trekking'],
        weatherInfo: "Greener and wetter than Kaza.",
        bestTime: "June to October",
        gettingThere: "Turn right from Attargo bridge near Kaza.",
        thingsToDo: ["Pin Parvati Trek base", "Stay in Mud", "Wildlife spotting"],
        faq: [
            { question: "What are Spiti Biosphere Reserve rules?", answer: "Strict 'Leave No Trace' policy. No camping near water bodies." },
            { question: "Zero-Waste homestays in Pin Valley?", answer: "Look for homestays in Mud Village that use solar cookers and traditional insulation." },
            { question: "Permit?", answer: "No special permit for Mud village." },
            { question: "Snow leopard?", answer: "Winter is best time. Summer sightings rare." },
            { question: "Mud Village stay?", answer: "Tara Guest house and other homestays available." },
            { question: "Is single-use plastic banned?", answer: "Yes, strictly enforced." },
            { question: "River?", answer: "Pin River. Turquoise color." }
        ],
        longContent: `<p>Contrasting with the brown of Spiti, <strong>Pin Valley</strong> offers shades of green and purple (in flowering season). It is a protected area for the endangered Snow Leopard and Siberian Ibex. The drive to <strong>Mud Village</strong>, the last village in the valley, is scenic and serene.</p>`
    },
    {
        slug: 'chitkul-last-village-india',
        title: 'Chitkul Travel Guide',
        subtitle: 'The Last Village',
        heroImage: '/hero/kinnaur.png',
        introTitle: 'End of the Road',
        introText: 'Chitkul is the last inhabited village on the Indo-Tibet border. The air here is the cleanest in India.',
        metaTitle: 'Chitkul Kinnaur | Last Village of India Tour',
        metaDescription: 'Visit Chitkul, the last village of India. Baspa river, wooden houses, and potatoes.',
        relatedTourId: 'rohru-kinnaur-expedition',
        features: ['Cleanest Air', 'Baspa River', 'Mathi Devi Temple', 'Potatoes'],
        weatherInfo: "Cool summers, snowy winters.",
        bestTime: "April to October",
        gettingThere: "24km from Sangla.",
        thingsToDo: ["Riverside picnic", "Visit 'Hindustan ka Aakhri Dhaba'", "Temple visit"],
        faq: [
            { question: "Drone ban border villages?", answer: "Strictly banned in Chitkul. ITBP monitors area." },
            { question: "Can we go to Tibet?", answer: "No, border is closed and manned by ITBP." },
            { question: "Is it cold?", answer: "Yes, chilly even in summer evenings." },
            { question: "Where to eat?", answer: "Hindustan Ka Aakhri Dhaba is famous." },
            { question: "Stay options?", answer: "Zostel Chitkul, homestays, and riverside camps." },
            { question: "Road condition?", answer: "Good till Sangla. Sangla-Chitkul is narrow." },
            { question: "Famous crop?", answer: "Chitkul Potatoes and Peas." }
        ],
        longContent: `<p>Chitkul is like a painting. Wooden houses with slate roofs, the crystal clear Baspa river flowing alongside, and snow-clad peaks in the backdrop. It is famous for its potatoes, considered some of the best in the world. A walk through the village lanes takes you back in time.</p>`
    },
    {
        slug: 'kalpa-kinnaur-guide',
        title: 'Kalpa Travel Guide',
        subtitle: 'Abode of Shiva',
        heroImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80',
        introTitle: 'Views of Kinner Kailash',
        introText: 'Kalpa offers the finest views of the sacred Kinner Kailash peak.',
        metaTitle: 'Kalpa Kinnaur Tourism | Hotels & Sightseeing',
        metaDescription: 'Best guide for Kalpa. Suicide point, Roghi village, and apple orchards.',
        relatedTourId: 'spiti-kinnaur-adventure',
        features: ['Kinner Kailash', 'Suicide Point', 'Roghi Village', 'Narayan Nagini Temple'],
        weatherInfo: "Pleasant days, cold nights.",
        bestTime: "April to October",
        gettingThere: "14km uphill from Reckong Peo.",
        thingsToDo: ["Morning sunrise view", "Walk to Suicide Point", "Visit Hu-Bu-Lan-Kar monastery"],
        faq: [
            { question: "Suicide point?", answer: "A sheer cliff with vertical drop. Safe if behind railing." },
            { question: "Kinner Kailash Jorkanden?", answer: "Both peaks visible. Kinner Kailash has the Shivling rock." },
            { question: "Best hotel?", answer: "HPTDC Kinner Kailash or private hotels like Grand Shamba." },
            { question: "Distance Peo?", answer: "30 mins drive uphill." },
            { question: "Apples?", answer: "Best apples in India grow here." },
            { question: "Peo SDM office open Saturdays?", answer: "Usually closed or half-day. Plan for weekdays." },
            { question: "Temple?", answer: "Narayan Nagini temple is architectural marvel." }
        ],
        longContent: `<p>Legend has it that Kalpa was the winter home of Lord Shiva. The imposing <strong>Kinner Kailash</strong> peak (6,050m) changes colors throughout the day. Kalpa is also famous for its high-quality apples and Chilgoza (pine nuts). A walk to the 'Suicide Point' offers vertiginous views of the Sutlej river miles below.</p>`
    },
    {
        slug: 'langza-hikkim-komic',
        title: 'Langza Hikkim Komic Tour',
        subtitle: 'The High Villages',
        heroImage: '/visual-journey/langza.png',
        introTitle: 'Touch the Sky',
        introText: 'A circuit visiting the Fossil Village, Highest Post Office, and Highest Village.',
        metaTitle: 'Langza Hikkim Komic Day Tour Spiti',
        metaDescription: 'Visit Hikkim Post Office, Komic Monastery, and Langza Buddha Statue.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['Fossils', 'Post Office', 'Highest Village', 'Buddha Statue'],
        weatherInfo: "Very windy and high UV.",
        bestTime: "May to October",
        gettingThere: "Day trip from Kaza.",
        thingsToDo: ["Post a postcard", "Find Ammonite fossils", "Visit Komic Monastery"],
        faq: [
            { question: "Waste cleanup in Langza?", answer: "Join 'Healing Himalayas' or Ecosphere volunteers on weekends." },
            { question: "Buy Yak Cheese?", answer: "Available at Komic monastery and Langza homestays." },
            { question: "Time required?", answer: "4-5 hours for the full loop from Kaza." },
            { question: "Postcard stamp?", answer: "Buy at post office. Postmaster puts seal." },
            { question: "Fossils?", answer: "Do not take them home. Buy replicas to support locals." },
            { question: "Altitude?", answer: "Komic is 4587m. Don't run/exert." },
            { question: "Stay?", answer: "Homestays available in Langza." }
        ],
        longContent: `<p>This trio of villages offers the quintessential Spiti experience. <strong>Langza</strong> is guarded by a massive Golden Buddha statue and is rich in marine fossils. <strong>Hikkim</strong> invites you to send a postcard from the world's highest post office—a charming old-school experience. <strong>Komic</strong>, the highest motorable village, houses a monastery with a stuffed Snow Leopard.</p>`
    },
    {
        slug: 'gue-mummy-spiti',
        title: 'Gue Mummy Guide',
        subtitle: 'The 500-Year-Old Monk',
        heroImage: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80',
        introTitle: 'Natural Mummification',
        introText: 'Visit the naturally preserved mummy of Monk Sangha Tenzin in Gue village.',
        metaTitle: 'Gue Mummy Spiti Valley | History & Location',
        metaDescription: 'See the 500-year-old mummy in Gue. Located near the Indo-Tibet border.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['Mummy', 'Border Village', 'Unique History'],
        weatherInfo: "Arid and dry.",
        bestTime: "May to October",
        gettingThere: "Detour near Sumdo checkpost.",
        thingsToDo: ["Visit Mummy Temple", "View Tibet border"],
        faq: [
            { question: "Gue Mummy ethics?", answer: "Do not make loud noise. Circumambulate clockwise." },
            { question: "Drone ban border villages?", answer: "Strictly banned in Gue. Very close to Tibet border." },
            { question: "Cost?", answer: "Free entry." },
            { question: "Is it creepy?", answer: "It's spiritual. The monk died meditating." },
            { question: "Location?", answer: "8km detour from Sumdo (Shimla-Kaza highway)." },
            { question: "Preservation?", answer: "No chemicals. Skin and teeth intact." },
            { question: "Photography?", answer: "Allowed." }
        ],
        longContent: `<p>In a glass box in the tiny village of Gue sits the remarkably well-preserved body of a monk, <strong>Sangha Tenzin</strong>. Discovered after an earthquake, the mummy has teeth, skin, and hair interacting, with no chemical preservation. It is a mystery of natural mummification and deep meditation.</p>`
    },
    {
        slug: 'dhankar-monastery-guide',
        title: 'Dhankar Monastery Guide',
        subtitle: 'Cliffhanger',
        heroImage: '/visual-journey/dhankar.png',
        introTitle: 'Palace on the Cliff',
        introText: 'Dhankar was the erstwhile capital of Spiti. The monastery hangs precariously on a cliff edge.',
        metaTitle: 'Dhankar Monastery & Lake Trek',
        metaDescription: 'Guide to Dhankar Monastery and the trek to Dhankar Lake.',
        relatedTourId: 'spiti-kinnaur-adventure',
        features: ['Dhankar Lake', 'Ancient Fort', 'Confluence View'],
        weatherInfo: "Windy.",
        bestTime: "May to October",
        gettingThere: "Between Tabo and Kaza.",
        thingsToDo: ["Trek to Dhankar Lake (1 hr)", "Explore old rooms"],
        faq: [
            { question: "Lake trek difficulty?", answer: "Moderate. Steep uphill. 45-60 mins." },
            { question: "Is monastery safe?", answer: "Old structure is fragile. Only few people allowed at a time." },
            { question: "Confluence?", answer: "Pin and Spiti rivers merge below." },
            { question: "Stay?", answer: "New monastery has guest house. Homestays in village." },
            { question: "Distance Kaza?", answer: "32km (~1 hour)." },
            { question: "Entry fee?", answer: "Donation based." },
            { question: "Wind?", answer: "Extremely windy location." }
        ],
        longContent: `<p><strong>Dhankar's</strong> setting is dramatic. Overlooking the confluence of the Spiti and Pin rivers, the complex hangs on a spur. A steep one-hour trek leads to the serene <strong>Dhankar Lake</strong>, offering reflections of the Manirang peak.</p>`
    },
    {
        slug: 'kunzum-pass-guide',
        title: 'Kunzum Pass Travel Guide',
        subtitle: 'Gateway to Spiti',
        heroImage: '/visual-journey/kunzum.png',
        introTitle: 'Pass of Goddesses',
        introText: 'At 4,590m, Kunzum La connects Lahaul and Spiti valleys.',
        metaTitle: 'Kunzum Pass Height & Road Status 2026',
        metaDescription: 'Status of Kunzum Pass. Connecting Manali to Kaza.',
        relatedTourId: 'manali-to-spiti-road-trip',
        features: ['High Pass', 'Stupas', 'Snow'],
        weatherInfo: "Always cold. Windy.",
        bestTime: "Late June to Early October",
        gettingThere: "On the Manali-Kaza road.",
        thingsToDo: ["Circumambulate Stupas", "Photo stop"],
        faq: [
            { question: "Kunzum Pass opening 2026?", answer: "Expected early June due to low snow this year." },
            { question: "Is it open?", answer: "Generally June to October." },
            { question: "Ritual?", answer: "Driver stops for blessings from Kunzum Mata." },
            { question: "Chandratal link?", answer: "Yes, turn for Chandratal is near Batal, close to pass." },
            { question: "Altitude?", answer: "4590m. Don't stay too long." },
            { question: "Snow?", answer: "Likely to see snow even in summer." },
            { question: "Road?", answer: "Dirt track. Very bumpy." }
        ],
        longContent: `<p>Kunzum Pass is more than a geographical divide; it is a spiritual one. Travelers must stop and pay respects at the temple of Kunzum Mata to ensure a safe journey. The views of the <strong>Bara-Shigri Glacier</strong> (second longest in the world) from here are breathtaking.</p>`
    },
    {
        slug: 'tabo-monastery-guide',
        title: 'Tabo Monastery Guide',
        subtitle: 'Ajanta of Himalayas',
        heroImage: 'https://images.unsplash.com/photo-1545652585-703c37351543?auto=format&fit=crop&q=80',
        introTitle: 'A Millennium of Peace',
        introText: 'Founded in 996 AD, Tabo is the oldest continuously operating Buddhist enclave.',
        metaTitle: 'Tabo Monastery Spiti | Oldest Monastery',
        metaDescription: 'Visit Tabo Monastery. Famous for ancient murals and mud statutes.',
        relatedTourId: 'spiti-kinnaur-adventure',
        features: ['Mud Architecture', 'Murals', 'Meditation Caves'],
        weatherInfo: "Warm days in summer.",
        bestTime: "May to October",
        gettingThere: "48km from Kaza.",
        thingsToDo: ["Morning prayers", "Visit meditation caves"],
        faq: [
            { question: "Farm-to-table in Tabo?", answer: "Tabo has vast apple and apricot orchards offering fresh meals." },
            { question: "Why 'Ajanta'?", answer: "Because of exquisite wall paintings (frescoes)." },
            { question: "Photography?", answer: "Strictly NO inside temples. Flash damages art." },
            { question: "Caves?", answer: "Meditation caves carved in hill opposite monastery." },
            { question: "Food?", answer: "Tabo has good cafes (Third Eye, Kunzum Top)." },
            { question: "Stay?", answer: "Monastery guest house is cheap and clean." },
            { question: "Distance Kaza?", answer: "48km (1.5 hours)." }
        ],
        longContent: `<p>Unlike other monasteries on hills, <strong>Tabo</strong> is situated in the valley floor. Its unassuming mud exterior hides a treasure trove of art inside. The walls are covered in exquisite frescoes depicting the life of Buddha, earning it the title 'Ajanta of the Himalayas'.</p>`
    },
    {
        slug: 'nako-lake-guide',
        title: 'Nako Lake Travel Guide',
        subtitle: 'Oasis in Desert',
        heroImage: '/visual-journey/nako.png',
        introTitle: 'Mirror Lake',
        introText: 'Nako is a high-altitude lake surrounded by willow and poplar trees.',
        metaTitle: 'Nako Lake Kinnaur | Village & Monastery',
        metaDescription: 'Visit Nako Lake. A serene stopover between Kinnaur and Spiti.',
        relatedTourId: 'spiti-kinnaur-adventure',
        features: ['Sacred Lake', 'Nako Monastery', 'Footprint of Padmasambhava'],
        weatherInfo: "Cool & Dry.",
        bestTime: "May to October",
        gettingThere: "On the Shimla-Kaza highway.",
        thingsToDo: ["Lake walk", "Visit Monastery"],
        faq: [
            { question: "Swimming?", answer: "No, sacred lake." },
            { question: "Village?", answer: "Nako village is labyrinth of stone/mud houses." },
            { question: "Monastery?", answer: "Nako Monastery dated 11th century." },
            { question: "Distance Kaza?", answer: "110km. Usually a lunch/stay stop." },
            { question: "Helipad?", answer: "Yes, Nako has a helipad." },
            { question: "Trees?", answer: "Willows and Poplars line the lake." },
            { question: "Food?", answer: "Good cafes overlooking the lake." }
        ],
        longContent: `<p>Nako village is a maze of stone houses and narrow alleys. The lake, though small, is spiritually significant. It is believed that Guru Padmasambhava meditated here, and his footprint is imprinted on a rock nearby.</p>`
    },
    {
        slug: 'baralacha-la-pass',
        title: 'Baralacha La Pass Guide',
        subtitle: 'Crossroads of Summits',
        heroImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&q=80',
        introTitle: 'Where Roads Meet',
        introText: 'At 4,890m, it connects Lahaul, Ladakh, and Spiti.',
        metaTitle: 'Baralacha La Pass | Manali Leh Highway',
        metaDescription: 'Guide to Baralacha La. Suraj Tal Lake and snow walls.',
        relatedTourId: 'manali-to-spiti-road-trip',
        features: ['Suraj Tal', 'High Altitude', 'Snow Walls'],
        weatherInfo: "Freezing.",
        bestTime: "June to September",
        gettingThere: "Manali-Leh Highway.",
        thingsToDo: ["See Suraj Tal", "Touch snow"],
        faq: [
            { question: "Is it dangerous?", answer: "Yes, snow blizzards common. 4890m altitude." },
            { question: "Suraj Tal?", answer: "Review just below pass. Start of Bhaga river." },
            { question: "Route?", answer: "Manali -> Keylong -> Jispa -> Baralacha La." },
            { question: "Mobile?", answer: "No network." },
            { question: "Food?", answer: "No dhabas on pass. Zingzingbar is nearest." },
            { question: "Road?", answer: "Smooth tar mostly (BRO maintained)." },
            { question: "Snow walls?", answer: "Massive snow walls in June." }
        ],
        longContent: `<p><strong>Baralacha La</strong> is beautiful and deadly. It is often covered in deep snow even in June. The stunning <strong>Suraj Tal</strong> (Sun Lake) lies just below the pass, sourcing the Bhaga river.</p>`
    },
    {
        slug: 'jispa-travel-guide',
        title: 'Jispa Travel Guide',
        subtitle: 'Riverside Halt',
        heroImage: 'https://images.unsplash.com/photo-1568495248636-6432d97bd949?auto=format&fit=crop&q=80',
        introTitle: 'Lahaul\'s Gem',
        introText: 'Jispa lies on the banks of the Bhaga river and is a favorite stop for Ladakh bikers.',
        metaTitle: 'Jispa Lahaul Valley | Camps & Hotels',
        metaDescription: 'Stay in Jispa. Riverside camps and hotels on Manali-Leh route.',
        relatedTourId: 'manali-to-spiti-road-trip',
        features: ['Bhaga River', 'Camping', 'Starry Nights'],
        weatherInfo: "Cold winds.",
        bestTime: "May to September",
        gettingThere: "20km from Keylong.",
        thingsToDo: ["Riverside walk", "Visit Gemur Monastery"],
        faq: [
            { question: "Hotel vs Camp?", answer: "Jispa is famous for riverside camping." },
            { question: "Altitude?", answer: "3200m. Good for acclimatization." },
            { question: "Distance Manali?", answer: "100km via Atal Tunnel." },
            { question: "Monastery?", answer: "Gemur monastery nearby." },
            { question: "Food?", answer: "Hotel Ibex is famous." },
            { question: "Fuel?", answer: "Fill at Tandi (30km back)." },
            { question: "Network?", answer: "Jio works well." }
        ],
        longContent: `<p>Jispa is defined by its width—a broad valley with the river flowing lazily. It creates a perfect setting for camping. It is a vital acclimatization stop for those heading to Leh or Baralacha La.</p>`
    },
    {
        slug: 'sissu-lahaul-guide',
        title: 'Sissu Travel Guide',
        subtitle: 'Atal Tunnel Gateway',
        heroImage: 'https://images.unsplash.com/photo-1596436889106-be35e843f974?auto=format&fit=crop&q=80',
        introTitle: 'The New Hotspot',
        introText: 'Just across the Atal Tunnel, Sissu greets you with a massive waterfall.',
        metaTitle: 'Sissu Lahaul Valley | Sissu Waterfall & Lake',
        metaDescription: 'Visit Sissu via Atal Tunnel. Waterfall, Lake, and Nursery.',
        relatedTourId: 'manali-to-spiti-road-trip',
        features: ['Sissu Waterfall', 'Sissu Lake', 'Poplar Trees'],
        weatherInfo: "Windy.",
        bestTime: "All Year (except heavy snow days).",
        gettingThere: "40km from Manali.",
        thingsToDo: ["Trek to waterfall", "Boating in lake"],
        faq: [
            { question: "Is Sissu completely closed to tourists from Jan 20 to Feb 28, 2026?", answer: "Yes, tourism is suspended for 40 days due to local deity rituals." },
            { question: "Can I still drive through Sissu via Atal Tunnel?", answer: "Yes, the highway remains open for transit to Keylong/Jispa. No sightseeing allowed." },
            { question: "Which adventure activities are banned?", answer: "All activities including Zipline, ATV rides, and boating in Sissu Lake are suspended." },
            { question: "Are hotels in Sissu taking bookings for Feb 2026?", answer: "No. Bookings are paused. Look for stays in Keylong or Manali instead." },
            { question: "Waterfall name?", answer: "Palden Lhamo Dhar." },
            { question: "Distance from Tunnel?", answer: "Just 6-7km from North Portal." },
            { question: "Day trip?", answer: "Perfect day trip from Manali." }
        ],
        longContent: `<p>Sissu has transformed from a quiet village to a bustling destination after the <strong>Atal Tunnel</strong> opened. The <strong>Palden Lhamo dhar waterfall</strong> is a spectacular sight, dropping from high cliffs.</p>`
    },
    {
        slug: 'shimla-manali-tour-package',
        title: 'Shimla Manali Tour Package',
        subtitle: 'The Classic Duo',
        heroImage: '/hero/shimla.png',
        introTitle: 'Best of Himachal',
        introText: 'The ultimate family holiday covering the two queens of hills.',
        metaTitle: 'Shimla Manali Tour Package 2026 | Family & Honeymoon',
        metaDescription: 'Book Shimla Manali tour. Mall road, Rohtang Pass, and Solang Valley.',
        relatedTourId: 'shimla-spiti-overland',
        features: ['Mall Road', 'Rohtang Pass', 'Hadimba Temple'],
        weatherInfo: "Pleasant summer, snowy winter.",
        bestTime: "All Year",
        gettingThere: "Road connectivity from Delhi/Chandigarh.",
        thingsToDo: ["Shopping", "Paragliding", "River Rafting"],
        faq: [
            { question: "Distance Shimla Manali?", answer: "250km (7-8 hours). Scenic route via Mandi." },
            { question: "Snow?", answer: "Dec to Feb in town. Solang/Rohtang has snow longer." },
            { question: "Honeymoon special?", answer: "Yes, flower bed decoration, candle light dinner provided." },
            { question: "Volvo?", answer: "Available from Delhi to both towns." },
            { question: "Toy Train?", answer: "Kalka-Shimla toy train is UNESCO heritage. Must do." },
            { question: "Adventure?", answer: "Paragliding in Solang, Rafting in Kullu." },
            { question: "Days?", answer: "6N/7D covering both is ideal." }
        ],
        longContent: `<p>While we specialize in offbeat tours, the classic <strong>Shimla-Manali circuit</strong> remains evergreen. From the colonial charm of Shimla's Ridge to the adventure sports in Manali's Solang Valley, this trip has something for everyone.</p>`
    },
    {
        slug: 'delhi-to-spiti-volvo',
        title: 'Delhi to Spiti Valley Trip',
        subtitle: 'Budget Travel',
        heroImage: '/hero/pabbar.png',
        introTitle: 'Bus to the Mountains',
        introText: 'How to reach Spiti Valley from Delhi using public transport/Volvo.',
        metaTitle: 'Delhi to Spiti Valley by Bus | Volvo & HRTC Guide',
        metaDescription: 'Budget guide to Spiti. HRTC buses, Volvo timings, and route.',
        relatedTourId: 'shimla-spiti-overland',
        features: ['Budget Friendly', 'HRTC Adventure', 'Local Experience'],
        weatherInfo: "N/A",
        bestTime: "June to September",
        gettingThere: "Delhi -> Shimla/Manali -> Kaza.",
        thingsToDo: ["Ride the HRTC bus", "Meet backpackers"],
        faq: [
            { question: "Direct Volvo?", answer: "No. Volvo till Shimla/Manali. Then HRTC/Taxi." },
            { question: "HRTC reliability?", answer: "High. Drivers are skilled." },
            { question: "Direct bus?", answer: "HRTC runs Reckong Peo to Kaza daily." },
            { question: "Cost?", answer: "Bus fare is very cheap (~₹1000 total)." },
            { question: "Comfort?", answer: "Low. Buses are ordinary/bumpy." },
            { question: "Booking?", answer: "Book Volvo online on HPTDC/Redbus. HRTC local at counter." },
            { question: "Time?", answer: "2 days travel." }
        ],
        longContent: `<p>Traveling to Spiti on a budget? The <strong>HRTC (Himachal Road Transport Corporation)</strong> is your lifeline. The bus ride from Shimla/Reckong Peo to Kaza is legendary for its thrill. It’s cheap, reliable, and offers the most authentic local experience.</p>`
    },
    {
        slug: 'spiti-trekking-expeditions',
        title: 'Spiti Trekking Expeditions',
        subtitle: 'Walk the Himalayas',
        heroImage: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80',
        introTitle: 'Trails of High Asia',
        introText: 'Explore Spiti on foot. Parang La, Pin Parvati, and Kanamo Peak.',
        metaTitle: 'Trekking in Spiti Valley | Parang La & Pin Parvati',
        metaDescription: 'Best treks in Spiti. Kanamo Peak, Parang La to Ladakh.',
        relatedTourId: 'spiti-4x4-expedition',
        features: ['Kanamo Peak (6000m)', 'Parang La', 'Homestay Treks'],
        weatherInfo: "Cold and dry.",
        bestTime: "July to September",
        gettingThere: "Treks start from Kaza/Kibber.",
        thingsToDo: ["Summit Kanamo", "Cross glaciers"],
        faq: [
            { question: "Snow blindness?", answer: "Wear UV400 sunglasses even on cloudy days." },
            { question: "Difficulty?", answer: "Spiti treks are high altitude (4000m+). Strenuous." },
            { question: "Kanamo Peak?", answer: "6000m peak. Non-technical but stamina needed." },
            { question: "Pin Parvati?", answer: "Technical crossover pass. Crevasses risk. Guide essential." },
            { question: "Homestay trek?", answer: "Yes, Langza-Komic-Demul is a great village trek." },
            { question: "Solo trekking?", answer: "Not advised due to harsh terrain/isolation." },
            { question: "Best shoes?", answer: "High ankle waterproof trekking boots." }
        ],
        longContent: `<p>For those who want to go beyond the road. Trekking in Spiti offers a landscape similar to Ladakh/Tibet. <strong>Kanamo Peak</strong> is a trekable 6000m peak requiring no technical skills. The <strong>Parang La</strong> trek takes you from Spiti to Tso Moriri in Ladakh over ancient trade routes.</p>`
    },
    {
        slug: 'sangla-valley-guide',
        title: 'Sangla Valley Travel Guide',
        subtitle: 'Valley of Flowers',
        heroImage: '/hero/kinnaur.png',
        introTitle: 'Lush Green Kinnaur',
        introText: 'Sangla is the most beautiful valley in Kinnaur, defined by the Baspa river.',
        metaTitle: 'Sangla Valley Kinnaur Tour | Camping & Hotels',
        metaDescription: 'Explore Sangla Valley. Kamru Fort, Trout Farm, and Buckwheat fields.',
        relatedTourId: 'rohru-kinnaur-expedition',
        features: ['Kamru Fort', 'Trout Fishing', 'Camping'],
        weatherInfo: "Pleasant.",
        bestTime: "April to October",
        gettingThere: "Detour from Karcham.",
        thingsToDo: ["Visit Kamru Fort", "Trout Farm"],
        faq: [
            { question: "Distance Shimla?", answer: "220km." },
            { question: "Kamru Fort?", answer: "Ancient multi-storied fort. Must climb." },
            { question: "Fishing?", answer: "Baspa river has trout. Permit needed for angling." },
            { question: "Camps?", answer: "Kinner Camps and Banjara Camps are famous." },
            { question: "Road?", answer: "Narrow gorge road from Karcham to Sangla." },
            { question: "Chitkul distance?", answer: "24km ahead of Sangla." },
            { question: "Weather?", answer: "Slightly warmer than Spiti. Lush green." }
        ],
        longContent: `<p>Sangla is a stark contrast to the barren Spiti. It is green, fertile, and filled with fruit orchards. The ancient <strong>Kamru Fort</strong>, standing sentinel over the valley, houses the idol of Kamakhya Devi brought from Assam.</p>`
    }
];
